name = "celeste-docs"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "docs.withceleste.ai"
custom_domain = true

[assets]
directory = "./out"
not_found_handling = "single-page-application"